// src/data/textureCatalog.ts
// The textures that REALLY exist in /public/textures.
// textureManifest.json is generated by scripts/build-texture-manifest.mjs (see package.json: predev / prebuild).
import manifest from './textureManifest.json';

export interface TextureEntry {
  id: string;
  name: string;
  path: string;
  finish: string;
}

const files: readonly string[] = manifest as string[];
const fileSet: ReadonlySet<string> = new Set<string>(files);

export const textureCatalog: TextureEntry[] = files.map((file) => ({
  id: `tex_${file}`,
  name: file.replace(/\.[^.]+$/, ''),
  path: `/textures/${encodeURIComponent(file)}`,
  finish: 'MDF Melamine Matt',
}));

export const TEXTURE_EXTENSIONS = ['webp', 'jpg', 'jpeg'] as const;

/**
 * `${prefix}${cleanBrand}.{webp|jpg|jpeg}` -> URL path of the first variant that exists in `available`, else null.
 * (The old engine only ever asked for .webp, so wood_agtturkey.jpg / stone_eggeraustria.jpeg could never load.)
 */
export function resolveConventionTexture(
  prefix: string,
  cleanBrand: string,
  available: ReadonlySet<string> = fileSet,
): string | null {
  if (!cleanBrand) return null;
  for (const ext of TEXTURE_EXTENSIONS) {
    const file = `${prefix}${cleanBrand}.${ext}`;
    if (available.has(file)) return `/textures/${encodeURIComponent(file)}`;
  }
  return null;
}
